"""updates

Revision ID: f6e8ca917d6a
Revises: 
Create Date: 2023-08-02 12:07:20.841746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e8ca917d6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset1', sa.String(), nullable=False),
    sa.Column('asset2', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset1', sa.String(), nullable=False),
    sa.Column('asset2', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickers',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('all_portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset1', sa.String(), nullable=False),
    sa.Column('asset2', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('asset_price1', sa.Float(), nullable=True),
    sa.Column('asset_price2', sa.Float(), nullable=True),
    sa.Column('zscore', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['all_portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_signals')
    op.drop_table('all_portfolio')
    op.drop_table('user')
    op.drop_table('tickers')
    op.drop_table('portfolio')
    op.drop_table('port')
    # ### end Alembic commands ###
